version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      SQLITE_DB_LOCATION: "/data/todo.db"
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
