name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: sudo npm test
        
      - name: Bump Version
        id: bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v'
          initial_version: '1.0.0'
      
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ steps.bump.outputs.new_version }} .

  push-and-deploy:
    needs: build-test
    runs-on: self-hosted
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ steps.bump.outputs.new_version }}

      - name: Deploy to Vagrant VM
        run: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ steps.bump.outputs.new_version }}
            docker stop todo-app || true
            docker rm todo-app || true
            docker run -d --name todo-app -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ steps.bump.outputs.new_version }}
