name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      SQLITE_DB_LOCATION: "/tmp/todo.db"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          npm install 
          npm test

  build-push:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Bump Version
        id: bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v'
          initial_version: '1.0.0'

      - name: Push Version Tag
        run: |
          git tag ${{ steps.bump.outputs.new_version }}
          git push origin ${{ steps.bump.outputs.new_version }}

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ steps.bump.outputs.new_version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
          

  deploy:
    needs: [build-test, build-push]
    runs-on: self-hosted
    steps:
      - name: Deploy to Vagrant VM
        run: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
            docker stop todo-app || true
            docker rm todo-app || true
            docker run -d --name todo-app -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest
